name: License Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Install package
        run: |
          pip install .

      - name: Install licheck
        run: |
          pip install git+https://github.com/NeonJarbas/lichecker

      - name: Install test dependencies
        run: |
          pip install pytest pytest-timeout

      - name: Test licenses
        run: |
          pytest test/license_tests.py